### ISSUE TITLE
func_button is broken

### ISSUE THREAD

**Issue by edgarbarney** [edgarbarney/halflife-planckepoch#3]
@Matnie of ModDB Says:
func_button does not work properly when using the "Don't Move" function, it also changes the texture of all other buttons when pressed. And in some strange way, only one button works at a time, others can be pressed but do not change the texture themselves, only one button changes the textures of all.

**Comment by bacontsu** [comment]
fixed by overfloater himself in this PR
https://github.com/edgarbarney/halflife-planckepoch/pull/24

fixes are taken from Trinity Engine 3.10
https://twhl.info/vault/view/6664

**Comment by edgarbarney** [comment]
Fixed in PR #24, commit 66ca61958cbadadf619f19c61356abc63d6e3e09
