### ISSUE TITLE
Implement Water Rise

### ISSUE THREAD

**Issue by edgarbarney** [edgarbarney/halflife-planckepoch#4]
For now, the water surface plane is static in the trinity engine. We've got to make it move with the water entity.

**Comment by bacontsu** [comment]
also fixed by Overfloater himself in this PR
https://github.com/edgarbarney/halflife-planckepoch/pull/24

fixes are taken from Trinity Engine 3.10
https://twhl.info/vault/view/6664

**Comment by edgarbarney** [comment]
Fixed in PR #24, commit 66ca61958cbadadf619f19c61356abc63d6e3e09
